apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes kubernetes.cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough verified
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
    personservice.local:53 {
        forward . /etc/resolv.conf
        hosts {
            192.168.86.200 personservice.local
            fallthrough
        }
        cache 30
        loop
        reload
        loadbalance
    }