apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-graphql-server
  labels:
    app: sb-graphql-server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-graphql-server
  template:
    metadata:
      labels:
        app: sb-graphql-server
    spec:
      containers:
        - name: sb-graphql-server
          image: mikew01/sb-graphql-server:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: PERSON_SERVICE_HOST
              value: person-service
            - name: PERSON_SERVICE_PORT
              value: "8080"