apiVersion: v1
kind: Service
metadata:
  name: sb-graphql-server
  labels:
    app: sb-graphql-server
    type: loadbalancer
spec:
  selector:
    app: sb-graphql-server
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: LoadBalancer