apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce #or ReadWriteMany if your storage supports it.
  resources:
    requests:
      storage: 5Gi
