apiVersion: v1
kind: Service
metadata:
  name: mn-grpc-client
  labels:
    app: mn-grpc-client
spec:
  selector:
    app: mn-grpc-client
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
  type:   LoadBalancer