apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-grpc-server
  template:
    metadata:
      labels:
        app: sb-grpc-server
    spec:
      containers:
        - name: sb-grpc-server
          image: mikew01/sb-grpc-server
          imagePullPolicy: Always
          ports:
            - containerPort: 50052 # gRPC port