---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBxnY9jQLDtUS8fQM1uq04ZVKszfxWjE3yTOTY1fzW1B5zpBMAheVNS5L5f+7SWXJXgHMMJCtp4EVoNZNLj4hjJXY8hNqEkDcPfMT1+NnU4/n85zwQFkasA/OHK0wTs00jp5tj9cg2f1TH7T04NfOh7KeCH72dJ1q4KXpHsA4lp0hDdRL6h0Y08qDUjvl+kkTJXNA5g01fPxh7dhIgvfsx+CQvHevhH+P/nD4bJUUFWZ3f+S9JO+RFmrxvlDfY3KtVtoUSq3SK+KzNgS/znEq/3jOHCAvtKpi98euanJ2ty8bjyrbupdwxlDOwAGT57M7BEthv4v72cNQSOa/L/COwA9k6YRjh4OSLnu38mSAckXVt2zra+hFKo3zQCmMYQyjvj6QEf/6kELNkZfQ8SeKRUcfd4p4Nq33kcGwhAR08wwFKRuUW+7zdvFEwE4tjqEr/E6caR+1fH7Y34e14Z36LInUA07+wbbYko7Jj8RE5zFdo9fs+3tr3+sDaAXr7+4KHKy9N37mieZPpc7EqqYiZrCBRuFVRbdIDh90bzd6y+oUGCWHRTV9mVS9YrpDVWJ+uQbkpbxMBm+gJlsks8xl8ddtIfhB5ntoRtIw0Ir9jN8Av1kOPbnqypCCTjtWGd8Maa84jZzSf6maf9we7XxqZs1CiH9eXoSknJJksHJfpFWO49T/aS/gTatqwFA3MV0e5Zscvsz1I2lq0Jqj6bmQES
    username: AgDG5NaCYHQ2RLFdPf2HXdKEDt05BIvr2JsDcGpF0CoZ3U26k/IqHodf6n4hV80iXiExKky8jM6yA/cWJTfMYLpEp2sV6d6GOObbpRXybMaymTUKHptSJMsV3qi6pRpnBJV24X+4/5vV5a7FR3nfSuGRszSf1zHPzvyEayTrbGV6Luy3EY+MOqBfo+DwaRu/aFTn5GpaI7WBuMK6l6qA+lOUA0BRLJIMZ1+ln5KTpAJq84B2XZfsDDRw9K1vS7M/dvg5LMUpZ4DXcbdfPLnB+PlaJ9VqMY8+H4EKP8o45L0VX7dad7xZFJYCA4ZYw8wm0ieBMmNaeEabEjujxwz0QD1JfqCSq1pPm9XPSuG2hNlD/NFd/2OY0TPm44F4iE7+T2tVqWUSYpq2ArR50bUJrovUSuW6olVXYCsXye+8ERK5b7Ub3yc2cmbmegdiH+mUJrpM/AHmMOegyn4I9aTHkrwaqpTAa1/3f+PvWTpgAgJ9p/ZpJtRf6m5CFyyWUqor68Crzx6RwbQmplRAPGg5Tb5B4VIfi4lKfs1gUchxbHae4tNfjkvfoP23IlZcT7GUOx5lbiE5+KFGGF//ZhKoeGfOgTR1+SraZ1SKon7kezlS1jHqnFykAjCdZ6jbe/cejL7TJuo2QzqtlZa9uVYcDIslL93Pa60foo84ttjqfAvHUB6xvzh3WFqhh5n99D2WAJGDjcKEa6A=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
